### DISCUSSION TITLE
false positives in pnpm lockfile

### DISCUSSION THREAD

**Discussion by elijaholmos** [zricethezav/gitleaks#1005] [Q&A]
I use CI for dependency management in one of my [public repos](https://github.com/elijaholmos/halo-discord-extension), and recently, a pull request was created that triggered several false positives from the Gitleaks GitHub action; see https://github.com/elijaholmos/halo-discord-extension/pull/51.

Is this an intentional feature with gitleaks? How am I able to stop all package versions with hashes (eg `0.11.0_hc4yn5f4ebzhrwwrb4uuunvgqi`) from being caught by gitleaks in the future?

**Comment by maltemorgenstern** [comment]
Hey @elijaholmos.
https://github.com/gitleaks/gitleaks/pull/1109 added your `pnpm-lock.yaml` to the global allow list. That change is not released yet, but should be included in the next version.

Otherwise you can create a custom `gitleaks.toml` and add this file to the global allow list: https://github.com/gitleaks/gitleaks#configuration
```toml
title = "Custom gitleaks config"

# extend from the default gitleaks toml
[extend]
useDefault = true

[allowlist]
description = "Exclude pnpm lock files"
paths = ['''pnpm-lock.yaml''']
```

Regards
Malte
