### DISCUSSION TITLE
Passwords inside a Postman Collection JSON file are not detected

### DISCUSSION THREAD

**Discussion by maksymgendin** [zricethezav/gitleaks#1248] [Ideas]
Dear community,

I found out that gitleaks doesn't detect passwords inside a Postman Collection JSON file. The structure is the following:

```
{
    "key": "password",
    "value": "my_secret_password",
    "type": "string"
}
```

Any chance that you could build some senseful default rule for that?

**Comment by rgmz** [comment]
Here's a naive rule that should be able to pick this up:

```toml
# https://www.postmanlabs.com/postman-collection/Collection.html
[[rules]]
id = "postman-collection"
description = ""
regex = '''(?i)"key"\s*:\s*"(?:key|api|token|secret|client|passwd|password|auth|access)"\s*,\s*"value"\s*:\s*"(.+?)",?'''
secretGroup = 1
keywords = ["key", "api", "token", "secret", "client", "passw", "password", "auth", "access"]
path = '''\.postman_collection(\.json)?$'''
[rules.allowlist]
regexes = [ 
   '''^\{\{[a-zA-Z][a-zA-Z_-]*\}\}$''', # https://learning.postman.com/docs/sending-requests/variables/#variables-quick-start
]
```

For example:
```json
{
    "key": "password",
    "value": "my_secret_password",
    "type": "string"
}

{
    "key": "password",
    "value": "my_secret_password"
}
```
