### DISCUSSION TITLE
Help needed: Gitleaks configuration to ignore test files and detect JWT tokens

### DISCUSSION THREAD

**Discussion by nh916** [zricethezav/gitleaks#1431] [Q&A]
I'm having some trouble configuring Gitleaks to both ignore my pytest test files and correctly detect JWT tokens within my project. I've set up my `.gitleaks.toml` file to extend the default configuration and added rules to ignore files that start or end with 'test' or 'tests'. Despite this, Gitleaks isn't detecting a JWT token I've deliberately placed in my README file to verify that gitleaks is working properly

Here's my current `.gitleaks.toml` configuration:

```toml
# Title for the gitleaks configuration file.
title = "Gitleaks configuration for my python project"

# Extend the default gitleaks configuration
[extend]
useDefault = true

# Global allowlist configuration to ignore files that start or end with 'test' or 'tests'
[allowlist]
description = "Ignore files that start or end with 'test' or 'tests' that are used for pytest"
paths = [
  '''.*\/test.*$''',       # exclude any files or directories containing 'test'
  '''.*\/tests.*$''',      # exclude any files or directories containing 'tests'
]
```

When I run `gitleaks detect --source . --config .gitleaks.toml -v`, it doesn't find any leaks, even though there's a JWT token in the README file and I should get some kind of an error.

Output:
```plaintext
3:56PM INF 1250 commits scanned.
3:56PM INF scan completed in 700ms
3:56PM INF no leaks found
```

I've tried writing the configuration in many ways, but am still getting errors. I've also tried updating to the latest version of Gitleaks, but the issue persists. Am I missing something in my configuration? How can I ensure that Gitleaks ignores the test files and still detects JWT tokens properly?

Any help or guidance would be greatly appreciated!

Thank you!
