### DISCUSSION TITLE
Ignoring whole commits with .gitleaksignore?

### DISCUSSION THREAD

**Discussion by ChrisHolman** [zricethezav/gitleaks#1645] [General]
Is there any way to ignore entire commits with the .gitleaksignore file? 

Our devs messed with the history of a branch, which means some historical secrets (which are false positives) are now being treated as a change and flagging as secrets. There are over a thousand occurrences. 

I want to avoid adding thousands of lines to the .gitleaksignore file if possible.

**Comment by bplaxco** [comment]
@ChrisHolman I don't think it's possible in the .gitleaksignore, but you should be able to add them in a `.gitleaks.toml` in the root of the repo.

Something like:

```toml
[extend]
useDefault = true

[[allowlists]]
description = "ignore specific commits"
commits = [
 # add commits here
]
```
