### DISCUSSION TITLE
Adding multiple allowlist entries

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [zricethezav/gitleaks#1861] [Q&A] [answered]
For readability and clarity, I want to add multiple allowlist entries.

However the following approach

```toml
[[allowlist]]
description = "This key is intentionally committed to GitHub as it is used for this reason"
regex = '''(?i)wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY'''

[[allowlist]]
description = "This key is also committed to Github for that reason, so be aware of it"
regex = '''(?i)wJalrXUtnFEMI/K7MDENG/bPxRfiCYANOTHEREXAMPLEKEY'''
````

Fails with:

```
FTL Failed to load config error="1 error(s) decoding:\n\n* 'AllowList' expected a map, got 'slice'"
```

What is the best way to approach this? (or at least keep some form of documentation about why is something allowed?

**Comment by rgmz** [comment]
Multiple allowlists need to be pluralized. The singular `allowlist` is kept for backwards-compatibility, but only works with a single entry (`[allowlist]`).
https://github.com/gitleaks/gitleaks?tab=readme-ov-file#configuration

```toml
[[allowlists]]
description = "This key is intentionally committed to GitHub as it is used for this reason"
regex = '''(?i)wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY'''

[[allowlists]]
description = "This key is also committed to Github for that reason, so be aware of it"
regex = '''(?i)wJalrXUtnFEMI/K7MDENG/bPxRfiCYANOTHEREXAMPLEKEY'''
```

**Comment by pantelis-karamolegkos** [comment]
Thanks! That seems to do the trick, I am not however getting

```
error="[[allowlists]] must contain at least one check for: commits, paths, regexes, or stopwords
```

**Reply by rgmz** [reply, marked as answer]
Ah, that's another syntax error. `[[allowlists]]` takes a list of patterns, unlike `[[rules]]`, so you need to change `regex: string` -> `regexes: []string`.
```diff
[[allowlists]]
description = "This key is also committed to Github for that reason, so be aware of it"
-regex = '''(?i)wJalrXUtnFEMI/K7MDENG/bPxRfiCYANOTHEREXAMPLEKEY'''
+regexes = ['''(?i)wJalrXUtnFEMI/K7MDENG/bPxRfiCYANOTHEREXAMPLEKEY''']
```


Example from the docs:
```toml
[[allowlists]]
description = "global allow list"
commits = [ "commit-A", "commit-B", "commit-C"]
paths = [
  '''gitleaks\.toml''',
  '''(.*?)(jpg|gif|doc)'''
]
# note: (global) regexTarget defaults to check the _Secret_ in the finding.
# Acceptable values for regexTarget are "match" and "line"
regexTarget = "match"
regexes = [
  '''219-09-9999''',
  '''078-05-1120''',
  '''(9[0-9]{2}|666)-\d{2}-\d{4}''',
]
```
