### DISCUSSION TITLE
Difference between allowlists and rules allowlists

### DISCUSSION THREAD

**Discussion by pantelis-karamolegkos** [zricethezav/gitleaks#1880] [Q&A] [answered]
What is the difference between adding to `.gitleaks.toml` 

this

```toml
[[rules]]
id = "generic-api-key"

    [[rules.allowlists]]
    description = "A false positive high entropy string"
    regexes = [
        '''<a-false-positive-high-entropy-string>'''
    ]
```

and this

```toml
[[allowlists]]
description = "A false positive high entropy string"
regexTarget = "match"
regexes = [
   '''<a-false-positive-high-entropy-string>'''
]
```
