### ISSUE TITLE
FTL  error="flag accessed but not defined: log-opts"

### ISSUE THREAD

**Issue by basictheprogram** [zricethezav/gitleaks#1007]
**Describe the bug**
Upgraded gitleaks to 8.14.0 and now multiple different repositories throw the same error
```
Detect hardcoded secrets.................................................Failed
- hook id: gitleaks
- exit code: 1

○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

7:49PM FTL  error="flag accessed but not defined: log-opts"
```

**To Reproduce**
Pre-commit hook
```
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.14.0
    hooks:
      - id: gitleaks
```
$ pre-commit run --all-files

**Expected behavior**
The pre-commit hook would not throw an error

**Basic Info (please complete the following information):**
 - OS:
```
ProductName:    macOS
ProductVersion: 12.6
BuildVersion:   21G115
```
 - Gitleaks Version:  v8.14.0

cc @zricethezav
