### ISSUE TITLE
gitleaks failed to detect secret when multiple rules are defined

### ISSUE THREAD

**Issue by carelschoeman** [zricethezav/gitleaks#1017]
**Describe the bug**
gitleaks failed to detect secret when multiple rules are defined

**To Reproduce**

I created a basic git repo with a single text file, _file.txt_, with content

```
Secret=P@ssw0rd
```

I also added a _.gitleaks.toml_ file with the following content

```
title = "gitleaks config"

[allowlist]
description = "allowlists"
regexes = [
	'''PASSWORD_GOES_HERE''',
    '''PLACEHOLDER_FOR_PASSWORD''',
    '''<YourStrong!Passw0rd>''',
    '''__AntiXsrfToken''',
    '''SECRET_DO_NOT_PASS_THIS_OR_YOU_WILL_BE_FIRED'''
]
paths = [
	'''(.*?)(jpg|gif|doc|pdf|bin|toml)$'''
]

[[rules]]
description = "Creds in text files"
regex = '''(i?)Secret'''
path = "(i?)txt"
```

In my test case I simply staged it and scanned it using  `gitleaks protect --staged`.

This found my leak: 

> WRN leaks found: 1

Then I added another rule so that _.gitleaks.toml_ looks like:

```
title = "gitleaks config"

[allowlist]
description = "allowlists"
regexes = [
	'''PASSWORD_GOES_HERE''',
    '''PLACEHOLDER_FOR_PASSWORD''',
    '''<YourStrong!Passw0rd>''',
    '''__AntiXsrfToken''',
    '''SECRET_DO_NOT_PASS_THIS_OR_YOU_WILL_BE_FIRED'''
]
paths = [
	'''(.*?)(jpg|gif|doc|pdf|bin|toml)$'''
]

[[rules]]
description = "Creds in text files"
regex = '''(i?)Secret'''
path = "(i?)txt"

[[rules]]
description = "Creds in json files"
regex = '''(i?)Secret'''
path = '''(i?)json'''
```

Note: all examples I could find on the internet shows that additional rules are configured using the second `[[rules]]` mechanism.

When scanning it does not find my secret

> INF no leaks found

If I swop the 2 rules in the config so that the text one is last it finds the leak again.

**Expected behavior**
I expect secrets to be detected regardless of the order of the rules.

**Basic Info (please complete the following information):**
 - OS: Microsoft Windows 10 Enterprise (10.0.19044 Build 19044)
 - Gitleaks Version: 8.14.1 (x64)

cc @zricethezav

**Comment by zricethezav** [comment]
@carelschoeman def a bug, thanks for bringing this to my attention. Gonna take a look 🔎 🕵🏻

**Comment by zricethezav** [comment]
@carelschoeman The reason you are experiencing this behavior is because there is no `id` value set in your rules. Therefore, for both rules, the `id` defaults to `""`. The internal config structure keeps a map of rules and uses the `id` as the key. So every rule without an `id` will be overriding the previous rule. 

I need to update the documentation in the README to explicitly state that `id` is a required field for all rules.

**Comment by zricethezav** [comment]
@carelschoeman changing the config to this fixes your issue

```toml
title = "gitleaks config"

[allowlist]
description = "allowlists"
regexes = [
	'''PASSWORD_GOES_HERE''',
    '''PLACEHOLDER_FOR_PASSWORD''',
    '''<YourStrong!Passw0rd>''',
    '''__AntiXsrfToken''',
    '''SECRET_DO_NOT_PASS_THIS_OR_YOU_WILL_BE_FIRED'''
]
paths = [
	'''(.*?)(jpg|gif|doc|pdf|bin|toml)$'''
]

[[rules]]
description = "Creds in text files"
id = "secret-in-text"
regex = '''(i?)Secret'''
path = "(i?)txt"

[[rules]]
description = "Creds in json files"
id = "secret-in-json"
regex = '''(i?)Secret'''
path = '''(i?)json'''
```
