### ISSUE TITLE
Error: unknown option "staged" when running pre-commit with docker_image language

### ISSUE THREAD

**Issue by kbroughton** [zricethezav/gitleaks#1022]
**Describe the bug**
I'm seeing the [unsafe directory bug](https://github.com/zricethezav/gitleaks/pull/883)
but I'm using the most recent container 
zricethezav/gitleaks:v8.15.0                                                            
344cf751f79b   7 days ago      36.1MB

**To Reproduce**
Use the .pre-commit-config.yaml as suggested [here](https://github.com/zricethezav/gitleaks/blob/master/.pre-commit-hooks.yaml)

echo '-----BEGIN RSA PRIVATE KEY-----' > dirty
git add .
pre-commit

**Expected behavior**
The hook should run the same when using "language" docker_image as when run using golang (or system).

**Screenshots**
<img width="823" alt="Screen Shot 2022-10-20 at 11 31 34 AM" src="https://user-images.githubusercontent.com/10562482/197007716-283bfadb-cba6-4c9f-8a60-af5f63944ab0.png">

**Basic Info (please complete the following information):**
 - OS: osx monterrey 12.6
 - Gitleaks Version:  v8.15.0

**Additional context**
The above output comes when I have the following .pre-commit-config.yaml

```
repos:
- repo: https://github.com/zricethezav/gitleaks
  rev: v8.15.0
  hooks:
    - id: gitleaks
      name: gitleaks via dockerized system call
      language: system
      entry: gitleaks

# I would prefer to use the docker_image language but
# it seems that the required -v mount is only available
# for "docker" language which doesn't require user installs

- repo: local
  hooks:
  # - id: gitleaks
  #   name: Detect hardcoded secrets
  #   description: Detect hardcoded secrets using Gitleaks
  #   entry: gitleaks protect --verbose --redact --staged
  #   language: golang
  #   pass_filenames: false
  #   verbose: true
  - id: gitleaks-docker2
    name: Detect hardcoded secrets via protect docker_image
    description: Detect hardcoded secrets using Gitleaks
    entry: zricethezav/gitleaks:v8.15.0 protect --verbose --staged --redact --source /src

```

The "system" call is made using a docker wrapper installed to /usr/local/bin/gitleaks
```
#!/bin/bash
docker run -v `pwd`:/path zricethezav/gitleaks:latest -c /path/.gitleaks.toml --source=/path protect  --staged --verbose
```
Oddly, using "system" and calling the same command I don't see the --staged problem.

I'm wondering if the -v path might not be mounting correctly, but looking at the source code for docker_image.py it 
seems to be calling the docker_cmd which does mount PWD to /src.

cc @zricethezav
