### ISSUE TITLE
GitLeaks not ignoring folder (pre-commit)

### ISSUE THREAD

**Issue by theprobugmaker** [zricethezav/gitleaks#1023]
**Describe the bug**

I commented before on [another issue](https://github.com/zricethezav/gitleaks/issues/995) but I decided to create this issue to track the problem better.

Imagine that I have a folder called `testdata` which contains keys such as TLS for testing purposes and I want to ignore them when using `pre-commit`. The problem is that it doesn't matter how I configure `.gitleaks.toml` file it will either ignore all rules or it won't allow me to commit the keys from `testdata` at all.

**To Reproduce**

I created an example repository: https://github.com/theprobugmaker/gitleaks-bug

You just need to follow the steps from the `README.md`.

---

Approach 1:

```toml
[[rules]]
[rules.allowlist]
paths = ['''testdata''', '''.*/testdata/.*''', '''.*\/testdata\/.*''']
```

Approach 2:

```toml
[rules.allowlist]
paths = ['''testdata''', '''.*/testdata/.*''', '''.*\/testdata\/.*''']
```

> Pretty much doesn't matter what pattern I put here it won't work

I even tried using the following:

```toml
[extend]
useDefault = true
```

It will ignore the rules I created and warn all the keys even the ones inside `testdata`

**Expected behavior**

In theory, GitLeaks should allow the `some.key` from the `testdata` folder and warn about the `some.key` from the root.

**Basic Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Gitleaks Version: v8.14.1

cc @zricethezav @weineran
