### ISSUE TITLE
Version of Tidy is unsupported 

### ISSUE THREAD

**Issue by stiliajohny** [zricethezav/gitleaks#1057]
**Describe the bug**

The version of `tidy` that is required is higher than the version go: go.mod file indicates go 1.19, but maximum version supported by tidy is 1.18
**To Reproduce**

Follow the installations steps 
git clone and make build on a ubuntu-latest container

**Expected behavior**

**Screenshots**
<img width="1333" alt="image" src="https://user-images.githubusercontent.com/17669235/207598406-aa1dbb32-5caf-4992-b5f4-a3958ba857c8.png">

**Basic Info (please complete the following information):**
 - OS:
 - Gitleaks Version:

**Additional context**

cc @zricethezav

**Comment by weineran** [comment]
@stiliajohny Thanks for reporting this. I am trying to reproduce, but so far unable. What version of go are you using?

```
$ go version
go version go1.19 linux/amd64
```

**Comment by stiliajohny** [comment]
```yml
  run-gitleak:
    runs-on: ubuntu-latest
    steps:
      - name: Get the output from the gitleaks step
        run: |
          pwd
          ls -la
          whoami
          go version
```

gives me 
```bash
total 8
drwxr-xr-x 2 runner docker 40[9](https://github.com/ITV/pv-workflows-app/actions/runs/3696364299/jobs/6259959894#step:2:10)6 Dec 14 15:41 .
drwxr-xr-x 3 runner docker 4096 Dec 14 15:41 ..
runner
go version go1.18.8 linux/amd64
```
