### ISSUE TITLE
Result disparity Golang vs Docker

### ISSUE THREAD

**Issue by mozo95** [zricethezav/gitleaks#1068]
Hey everyone, happy christmas!

**Describe the bug**
I was testing the pre-commit configuration and found different results when running with:
`language: docker_image`
and
`language: docker_image`

**To Reproduce**
.pre-commit-config.yaml for Docker file
```
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.15.2
    hooks:
      - id: gitleaks-docker
        name: Detect hardcoded secrets
        description: Detect hardcoded secrets using Gitleaks
        entry: zricethezav/gitleaks protect --verbose --redact --staged --source=.
        language: docker_image
```

.pre-commit-config.yaml for Go
```
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.15.2
    hooks:
      - id: gitleaks
        name: Detect hardcoded secrets
        description: Detect hardcoded secrets using Gitleaks
        entry: gitleaks protect --verbose --redact --staged --source=.
        language: golang
```

**Expected behavior**
For testing purposes I added a file with following content to a commit
{"api_key": "XXXXX", "username": "test", "password": "test"}

**Screenshots**
Results when run with Docker Image
<img width="570" alt="image" src="https://user-images.githubusercontent.com/57413382/209661283-0d49033b-5cc4-49d5-a128-8257a5fb3c98.png">

Results when run with Go
<img width="568" alt="image" src="https://user-images.githubusercontent.com/57413382/209661354-24799296-97c2-47b9-b14d-b26f6d318314.png">

**Basic Info (please complete the following information):**
 - OS: ProductName: macOS ProductVersion:12.6 BuildVersion:	21G115
 - Gitleaks Version: 5.12.0 and zricethezav/gitleaks:latest

cc @zricethezav
