### ISSUE TITLE
Allowlist may not be working as expected, per Discord

### ISSUE THREAD

**Issue by robwilkerson** [zricethezav/gitleaks#1279]
**Describe the bug**
Following up on a [message posted in Discord](https://discord.com/channels/1102689410522284044/1102691187430793327/1164193664516505713), I've been running gitleaks with the out-of-the-box config quite nicely on a number of projects for some time. Recently, though, I've bumped into a false positive in one repository that I can't seem to whitelist successfully. I'm running the following command during CI:

```
docker run -v "$(pwd):/scanpath" zricethezav/gitleaks:latest detect --source="/scanpath" --verbose --log-opts="${TRAVIS_COMMIT_RANGE/.../..}"
```

The false positive report looks like this:

```
Finding:     ...taxonomy_term:coswd_author:db5a350d-edc6-456b-b330-6b262d7652f8''
Secret:      db5a350d-edc6-456b-b330-6b262d7652f8
RuleID:      generic-api-key
Entropy:     3.638830
File:        src/config/default/field.field.node.blog.field_original_author.yml
Line:        10
Commit:      81d2705b83a51cbd8c5ba67781ab17a57c6790c9
Author:      <REDACTED>
Email:       <REDACTED>
Date:        2023-10-13T18:27:18Z
Fingerprint: 81d2705b83a51cbd8c5ba67781ab17a57c6790c9:src/config/default/field.field.node.blog.field_original_author.yml:generic-api-key:10
```

I've created a `.gitleaks.toml` file in my project root that I'd like to use to _extend_ the base config and have tried a few ways to whitelist this particular discovery but I can't seem to make it go away. My current config looks like this:

```
[extend]
useDefault = true

[rules.allowlist]

regexTarget = "line"
regexes = [
    "taxonomy_term:coswd_author",
]
```

I've attached the erroring file, in case that helps. It was suggested in the Discord that this _should_ work and that I should open a ticket.

**To Reproduce**
All I'm really doing is running the command above. Until now, I've needed to make zero changes from the default config.

**Expected behavior**
No found exposure, as long as the `allowlist` is correct.

**Basic Info (please complete the following information):**
 - OS: Ubuntu on the CI platform.
 - Gitleaks Version: `latest`

cc @zricethezav

**Comment by robwilkerson** [comment]
I forgot to add the content of the file that's throwing.

```
uuid: cdec82bf-93a2-469b-86a8-a495257dd662
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_original_author
    - node.type.blog
    - taxonomy.vocabulary.coswd_author
  content:
    - 'taxonomy_term:coswd_author:db5a350d-edc6-456b-b330-6b262d7652f8'
id: node.blog.field_original_author
field_name: field_original_author
entity_type: node
bundle: blog
label: 'Original Author'
description: ''
required: false
translatable: false
default_value:
  -
    target_uuid: db5a350d-edc6-456b-b330-6b262d7652f8
default_value_callback: ''
settings:
  handler: 'default:taxonomy_term'
  handler_settings:
    target_bundles:
      coswd_author: coswd_author
    sort:
      field: name
      direction: asc
    auto_create: false
    auto_create_bundle: ''
field_type: entity_reference
```
