### ISSUE TITLE
Whitelisting per-rule?

### ISSUE THREAD

**Issue by avishnyakov** [zricethezav/gitleaks#255]
v2 config looks good. 
https://github.com/zricethezav/gitleaks/wiki/config-toml

Would it be useful to have white-listing per rule?
Right now, white-listing is global - for both files and strings. It is too broad, would be much nicer to have per-rule whitelisting so that final .toml file does not become fat and unmanageable.

**Comment by rgmz** [comment]
I was just thinking about this, in addition to per-filetype whitelists.

Contrived examples:
**Per-Rule Whitelist**
```toml
[[rules]]
description = "Generic client secret"
regex = '''(?i)client(_|-)?secret(.{0,20})?['|"][0-9a-zA-Z]{32,45}['|"]'''
tags = ["key", "API", "generic"]
[[rules.whitelist]]
# $VENDOR provides everyone the same hard-coded client secret.
# (Yes, this actually happens)
regexes = ["AA97B177-9383-4934-8543-0F91A7A02836"]
```

**Per-Filetype(s) Whitelist**
```toml
[[whitelist.rules]]
description = "Ignore common Jenkinsfile methods)"
regexes = ["withCredentials", "usernamePassword", "usernameColonPassword"]
filetypes = ['''(.*)?Jenkinsfile$''']
```
