### ISSUE TITLE
Global allowlist repos doesn't work

### ISSUE THREAD

**Issue by cybervizay** [zricethezav/gitleaks#427]
**Describe the bug**
I am trying to whitelist (allowlist) some of the repositories in my org. I have specified following `config.toml`
```toml
title = "gitleaks config"

[[rules]]
	description = "Twitter Client ID"
	regex = '''(?i)twitter(.{0,20})?[0-9a-z]{18,25}'''
	tags = ["client", "Twitter"]
	
[allowlist]
    description = "allowed files/repos/commits"

    repos = [
                '''ngbp''',
		'''.*ngbp$''',
		'''https:\/\/github\.com\/ecajmer\/ngbp\.git''',
		'''ecajmer\/ngbp''',
		'''github\.com\/ecajmer\/ngbp'''
	]
```

All the repos regex specified belongs to same repo, but gitleakes doesn't follow allowlist.

**To Reproduce**
Using the above config file, run following command:
```shell
gitleaks --host=github --org=ecajmer --access-token=<access-token> --pretty -v --report=report.json --config config.toml
```

**Expected behavior**
It should not scan the repos specifed in `allowlist`.

**Screenshots**

**Basic Info (please complete the following information):**
 - OS: `Linux ThinkPad 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
 - Gitleaks Version: `v6`

cc @zricethezav
