### ISSUE TITLE
gitleaks and gitleaks-action behavior discrepancies  

### ISSUE THREAD

**Issue by chenrui333** [zricethezav/gitleaks#449]
**Describe the bug**
When I run `gitleaks --verbose  --repo=.` against repo1 in my local, I can see the leaks report.

```
WARN[2020-10-12T16:12:59-04:00] 22 leaks detected. 2275 commits scanned in 44 seconds 812 milliseconds 661 microseconds
```

But when I run with

```
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: gitleaks-action
        uses: zricethezav/gitleaks-action@master
```

It did not report any leaks but the success message as 

```
...
running gitleaks v6.1.2 with the following command👇
✅ SUCCESS! Your code is good to go!
```

**To Reproduce**

I am using gitleaks action and runs it against the master branch. 

**Expected behavior**
Show all the leaks in the gitleaks action output.

**Screenshots**

**Basic Info (please complete the following information):**
 - OS: MacOS (in my local), and Linux (for gitleaks action)
 - Gitleaks Version: 6.1.2 (for both)

**Additional context**
Another thing that I found there is no metrics report in the gitleaks action output.

cc @zricethezav
