### ISSUE TITLE
False positive matches for 'Twitter Client ID' using python import

### ISSUE THREAD

**Issue by LinqLover** [zricethezav/gitleaks#454]
We're getting a number of false-positive leaks using a python import statement:

```jsonc
{
	"line": "# from extended_twitter_collection import TwitterExtendedDatasetToDB",
	"lineNumber": 12,
	"offender": "twitter_collection import TwitterExtendedDatasetToDB",
	"commit": "364055528e97b3aa53ca8c4e97193613c6d0fd80",
	"rule": "Twitter Client ID",
	"file": "src/_fill_db.py",
	"tags": "client, Twitter",
	"operation": "addition"
	/* output truncated */
}
```

Is this intended? Should I fix this manually with a whitelist rule or should the regex pattern for twitter be refined?

**Comment by LinqLover** [comment]
Alright, this is how I ignored it:
```toml
[[whitelist.rules]]
description = "Ignore python imports"
regexes = ["from [\\w_\\.]+ import [\\w_\\.]+"]
```
