### ISSUE TITLE
v7 bugs: `[allowlist]...files` and `[[rules]].file` are no longer honored

### ISSUE THREAD

**Issue by pburkholder** [zricethezav/gitleaks#499]
**Describe the bug**
gitleaks 6.2.0 used to properly:

* exclude/allow file extensions in:
 ```[
[allowlist]
  files = [ '''regex''' ]
```
* detect filenames in
```
[[rules]]
	description = "File name extensions of credentials"
	file = '''regex'''
```

**To Reproduce**

I had to convince myself I hadn't screw something up, so I put the config files and my bats tests in their own repo. So, on MacOs

```
brew install bats-core #testing framework
git clone git@github.com:pburkholder/gitleaks-report.git
cd gitleaks-report
bats report.bats
```

You should see that all of v6 tests pass, but many of the v7 tests don't.

```
❯ bats report.bats
 ✓ detects an ipv4 pattern to show v7 generally works
 ✓ version of 6.2.0
 ✓ version of 7.2.0
 ✓ ingore ipv4-ish in svg
 ✗ ingore ipv4-ish in svg 7
   (in test file report.bats, line 77)
     `[ ${status} -eq 0 ]' failed
   Initialized empty Git repository in /private/var/folders/d5/1lby3jgx51qd6zftxp0mb4m80000gp/T/gittest.nn0LoH/.git/
 ✓ it fails a suspect filename extension in 6
 ✗ it fails a suspect filename extension in 7
   (in test file report.bats, line 89)
     `[ ${status} -eq 1 ]' failed
   Initialized empty Git repository in /private/var/folders/d5/1lby3jgx51qd6zftxp0mb4m80000gp/T/gittest.dvMboD/.git/
 ✓ it fails a suspect filename in 6
 ✗ it fails a suspect filename in 7
   (in test file report.bats, line 101)
     `[ ${status} -eq 1 ]' failed
   Initialized empty Git repository in /private/var/folders/d5/1lby3jgx51qd6zftxp0mb4m80000gp/T/gittest.zm4fCX/.git/

9 tests, 3 failures
```

**Expected behavior**

All of the tests should pass!

**Basic Info (please complete the following information):**

 - OS: MacOS 10.14
 - Gitleaks Version:

**Additional context**

Thanks for all your work!

cc @zricethezav

**Comment by pburkholder** [comment]
This seems to overlap a bit #496 in terms of `allowlist` behavior

**Comment by zricethezav** [comment]
@pburkholder could you provide me w/ your config? Are you following the correct syntax from https://github.com/zricethezav/gitleaks#rules-summary?

What gitleaks version are you using?

**Comment by pburkholder** [comment]
Hi. I see I forgot to provide links the issue description.  Anyhow: Version: 7.2.0

Rules from: https://github.com/pburkholder/gitleaks-report/blob/main/report.toml

```toml
title = "gitleaks config"

[[rules]]
	description = "IPv4 addresses"
	regex = '''\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b'''
	tags = ["IPv4", "IP", "addresses"]

[[rules]]
	description = "File name extensions of credentials"
	file = '''(?i)\.(pgpass|pem|key)'''
	tags = ["file"]

[[rules]]
	description = "File names of credentials"
	file = '''(?i)^(id_rsa|passwd|pgpass|shadow)'''

[allowlist]
	description = "image allowlists"
	files = ['''(.*?)(jpg|gif|doc|pdf|bin|svg)$''']
```
