### ISSUE TITLE
Github Actions / Ubuntu 18.04 > Option --commit=latest raises an "object not found" error

### ISSUE THREAD

**Issue by Cedric-Magnan** [zricethezav/gitleaks#521]
**Describe the bug**
The following command works perfectly fine on a laptop or on a VM but raises an error when started from Github Actions.
```sh
docker run --rm --name gitleaks -v $(pwd):/code/ zricethezav/gitleaks:v7.2.0 --path=/code/ --commit=latest
```
The same command does not raise an error when "--commit=latest" is removed from the command above.

**To Reproduce**
1) Create a new Github repository
2) Add a .github/workflows/CI.yml file to the repository with the following content:
```yaml
name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run gitleaks
      run: |
        echo $(pwd)
        ls -la $(pwd)
        docker run --rm --name gitleaks -v $(pwd):/code/ zricethezav/gitleaks:v7.2.0 --path=/code/ --commit=latest

```
3) Push the code to github

**Expected behavior**
The command should return an exit code 0, but instead, raises an "object not found" error. Git and docker are installed on the runner.

**Screenshots**
![image](https://user-images.githubusercontent.com/43343135/106898142-1bd61380-66f4-11eb-8cfe-0e34a455bbd6.png)

**Basic Info:**
 - OS: Runner ubuntu-latest (Ubuntu 18.04.5 LTS)
 - Gitleaks Version: v7.2.0

**Additional context**
This appears maybe for any Ubuntu 18.04.5 LTS device. However, I don't have access to other Ubuntu devices to test it.

cc @zricethezav
