### ISSUE TITLE
Gitlab ci job with Gitleaks "failed" randomly--> [object not found], but succeeded with --no-git flag

### ISSUE THREAD

**Issue by reuvenel** [zricethezav/gitleaks#542]
**Describe the bug**

When I try to run a simple job via Gitlab ci, I'm getting an error: **object not found**, but if I added **--no-git** flag, it works. I'm suspecting GitLab CI, so I ran it locally with different containers, and it worked like a charm.
I tried many times on Gitlab CI, but I don't know what the problem is.

**Update 11.04.21:**
It happens randomly when i edit the .yml file, I don't understand why is happening and how can I fix it.

**To Reproduce**

**.gitlab-ci.yml:**
```
stages:
  - secrets-detection
  
gitleaks:
  stage: secrets-detection
  image: 
    name: "zricethezav/gitleaks"
    entrypoint: [""]
  script: 
    - gitleaks -v --path=$PWD 
```

Running locally:

`$ docker run -it --rm -v "$(pwd):/$(pwd)" zricethezav/gitleaks -v --path=$PWD --config-path=$PWD/gitleaks.toml
`

**Screenshots**

<img width="987" alt="Screen Shot 2021-04-04 at 18 48 23" src="https://user-images.githubusercontent.com/61501266/113514315-8e3d6580-9576-11eb-85c1-bc02597dfd3a.png">
<img width="995" alt="Screen Shot 2021-04-04 at 18 49 37" src="https://user-images.githubusercontent.com/61501266/113514319-8f6e9280-9576-11eb-9476-38b6f710c884.png">

**Basic Info (please complete the following information):**
- Docker contanier: zricethezav/gitleaks
 - Gitleaks Version: 7.3.0
 * I tried all the versions from 6.0.0 to 7.4.0

cc @zricethezav
