### ISSUE TITLE
Whitelisting and/or merged GitLeaks configs not suppressing false-positives

### ISSUE THREAD

**Issue by SphenicPaul** [zricethezav/gitleaks#553]
**Describe the bug**
It currently appears that when using multiple configurations (merged as part of the execution of GitLeaks), the white/allow-listing isn't working correctly. 

NOTE: I'm a little new to use of GitLeaks so this could be a misunderstanding on my part, but further details below...

I'm currently using a global/packaged 'gitleaks.config' file as part of an execution of GitLeaks, and attempting to use this in conjunction with a repository-specific '.gitleaks.toml' file. The intention is that the **global** configuration contains all the rules to identify possible credentials/secrets (and some white/allowlist-ing) and the **repo** configuration contains other white/allow-listing to suppress any repository-specific, false positives.

Currently, I'm calling the following...

```"C:\pathTo\gitleaks-windows-amd64.exe" --path "C:/pathTo/SomeRepo" --config-path "C:\pathTo\gitleaks.config" --redact --unstaged --format=json --leaks-exit-code=0 --quiet --repo-config-path ".gitleaks.toml" --append-repo-config```

... which throws no errors with paths/config etc. and is outputting the following (for a .NET/C# `.cs` file I purposefully added a public, `ApiKey` property outputting a dummy key for testing purposes) on an uncommitted change to a file within a Git repository...

```{"line":"\t\tpublic string REDACTED;\r","lineNumber":2,"offender":"REDACTED","commit":"0000000000000000000000000000000000000000","repo":"SomeRepo","repoURL":"","leakURL":"","rule":"Generic Credential","commitMessage":"","author":"","email":"","file":"src\\SomeFolder\\SomeClasses\\SomeClass.cs","date":"1970-01-01T00:00:00Z","tags":"key, API, generic"}```

...where the **global** config (`gitleaks.config`) is (currently, relatively default based of one of the examples)...

```toml

title = "gitleaks config"

[[rules]]
	description = "AWS Access Key"
	regex = '''(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'''
	tags = ["key", "AWS"]

[[rules]]
	description = "AWS cred file info"
	regex = '''(?i)(aws_access_key_id|aws_secret_access_key)(.{0,20})?=.[0-9a-zA-Z\/+]{20,40}'''
	tags = ["AWS"]

[[rules]]
	description = "AWS Secret Key"
	regex = '''(?i)aws(.{0,20})?(?-i)['\"][0-9a-zA-Z\/+]{40}['\"]'''
	tags = ["key", "AWS"]

[[rules]]
	description = "AWS MWS key"
	regex = '''amzn\.mws\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'''
	tags = ["key", "AWS", "MWS"]

[[rules]]
	description = "Facebook Secret Key"
	regex = '''(?i)(facebook|fb)(.{0,20})?(?-i)['\"][0-9a-f]{32}['\"]'''
	tags = ["key", "Facebook"]

[[rules]]
	description = "Facebook Client ID"
	regex = '''(?i)(facebook|fb)(.{0,20})?['\"][0-9]{13,17}['\"]'''
	tags = ["key", "Facebook"]

[[rules]]
	description = "Twitter Secret Key"
	regex = '''(?i)twitter(.{0,20})?['\"][0-9a-z]{35,44}['\"]'''
	tags = ["key", "Twitter"]

[[rules]]
	description = "Twitter Client ID"
	regex = '''(?i)twitter(.{0,20})?['\"][0-9a-z]{18,25}['\"]'''
	tags = ["client", "Twitter"]

[[rules]]
	description = "Github"
	regex = '''(?i)github(.{0,20})?(?-i)['\"][0-9a-zA-Z]{35,40}['\"]'''
	tags = ["key", "Github"]

[[rules]]
	description = "LinkedIn Client ID"
	regex = '''(?i)linkedin(.{0,20})?(?-i)['\"][0-9a-z]{12}['\"]'''
	tags = ["client", "LinkedIn"]

[[rules]]
	description = "LinkedIn Secret Key"
	regex = '''(?i)linkedin(.{0,20})?['\"][0-9a-z]{16}['\"]'''
	tags = ["secret", "LinkedIn"]

[[rules]]
	description = "Slack"
	regex = '''xox[baprs]-([0-9a-zA-Z]{10,48})?'''
	tags = ["key", "Slack"]

[[rules]]
	description = "EC"
	regex = '''-----BEGIN EC PRIVATE KEY-----'''
	tags = ["key", "EC"]


[[rules]]
	description = "Google API key"
	regex = '''AIza[0-9A-Za-z\\-_]{35}'''
	tags = ["key", "Google"]


[[rules]]
	description = "Heroku API key"
	regex = '''(?i)heroku(.{0,20})?['"][0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}['"]'''
	tags = ["key", "Heroku"]

[[rules]]
	description = "MailChimp API key"
	regex = '''(?i)(mailchimp|mc)(.{0,20})?['"][0-9a-f]{32}-us[0-9]{1,2}['"]'''
	tags = ["key", "Mailchimp"]

[[rules]]
	description = "Mailgun API key"
	regex = '''(?i)(mailgun|mg)(.{0,20})?['"][0-9a-z]{32}['"]'''
	tags = ["key", "Mailgun"]

[[rules]]
	description = "PayPal Braintree access token"
	regex = '''access_token\$production\$[0-9a-z]{16}\$[0-9a-f]{32}'''
	tags = ["key", "Paypal"]

[[rules]]
	description = "Picatic API key"
	regex = '''sk_live_[0-9a-z]{32}'''
	tags = ["key", "Picatic"]

[[rules]]
	description = "Slack Webhook"
	regex = '''https://hooks.slack.com/services/T[a-zA-Z0-9_]{8}/B[a-zA-Z0-9_]{8}/[a-zA-Z0-9_]{24}'''
	tags = ["key", "slack"]

[[rules]]
	description = "Stripe API key"
	regex = '''(?i)stripe(.{0,20})?['\"][sk|rk]_live_[0-9a-zA-Z]{24}'''
	tags = ["key", "Stripe"]

[[rules]]
	description = "Square access token"
	regex = '''sq0atp-[0-9A-Za-z\-_]{22}'''
	tags = ["key", "square"]

[[rules]]
	description = "Square OAuth secret"
	regex = '''sq0csp-[0-9A-Za-z\\-_]{43}'''
	tags = ["key", "square"]

[[rules]]
	description = "Twilio API key"
	regex = '''(?i)twilio(.{0,20})?['\"][0-9a-f]{32}['\"]'''
	tags = ["key", "twilio"]

[[rules]]
	description = "Env Var"
	regex = '''(?i)(apikey|secret|key|api|password|pass|pw|host)=[0-9a-zA-Z-_.{}]{4,120}'''

[[rules]]
	description = "Port"
	regex = '''(?i)port(.{0,4})?[0-9]{1,10}'''
	[rules.allowlist]
		regexes = ['''(?i)port ''']
		description = "ignore export "



[[rules]]
	description = "Email"
	regex = '''[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}'''
	tags = ["email"]
	[rules.allowlist]
		files = ['''(?i)bashrc''']
		description = "ignore bashrc emails"


[[rules]]
	description = "Generic Credential"
	regex = '''(?i)(dbpasswd|dbuser|dbname|dbhost|api_key|apikey|secret|key|api|password|user|guid|hostname|pw|auth)(.{0,20})?['|"]([0-9a-zA-Z-_\/+!{}/=]{4,120})['|"]'''
	tags = ["key", "API", "generic"]
	# ignore leaks with specific identifiers like slack and aws
	[rules.allowlist]
		description = "ignore slack, mailchimp, aws"
		regexes = [
		    '''xox[baprs]-([0-9a-zA-Z]{10,48})''',
		    '''(?i)(.{0,20})?['"][0-9a-f]{32}-us[0-9]{1,2}['"]''',
		    '''(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'''
		]

[[rules]]
	description = "High Entropy"
	regex = '''[0-9a-zA-Z-_!{}/=]{4,120}'''
  	file = '''(?i)(dump.sql|high-entropy-misc.txt)$'''
	tags = ["entropy"]
    [[rules.Entropies]]
        Min = "4.3"
        Max = "7.0"
    [rules.allowlist]
        description = "ignore ssh key and pems"
        files = ['''(pem|ppk|env)$''']
        paths = ['''(.*)?ssh''']

[[rules]]
	description = "Potential bash var"
	regex='''(?i)(=)([0-9a-zA-Z-_!{}=]{4,120})'''
	tags = ["key", "bash", "API", "generic"]
        [[rules.Entropies]]
            Min = "3.5"
            Max = "4.5"
            Group = "1"

[[rules]]
	description = "WP-Config"
	regex='''define(.{0,20})?(DB_CHARSET|NONCE_SALT|LOGGED_IN_SALT|AUTH_SALT|NONCE_KEY|DB_HOST|DB_PASSWORD|AUTH_KEY|SECURE_AUTH_KEY|LOGGED_IN_KEY|DB_NAME|DB_USER)(.{0,20})?['|"].{10,120}['|"]'''
	tags = ["key", "API", "generic"]

[[rules]]
	description = "Files with keys and credentials"
    file = '''(?i)(id_rsa|passwd|id_rsa.pub|pgpass|pem|key|shadow)'''


```

... and the **repo** config (`.gitleaks.toml`) is as follows (Note: I added the `cs` to this, for testing this)...

```toml
# Global allowlist
[allowlist]
	description = "global allowlists"
	files = [
		'(.*?)(jpg|gif)$',
		'(.*?)(doc|pdf|bin|cs)$'
		]
	regexes = [
	    '(.*?)gitleaks:allow'
	]
```

**To Reproduce**
Use of above two configs and the call to GitLeaks.

**Expected behavior**
I'd expect all the `.cs` files within the repository to be white/allow-listed and as a result, these would **not** appear as possible 'leaks' identified by GitLeaks.

I've also tried this whilst using the file name and the full path explicitly but again, these weren't suppressed.

**Screenshots**
n/a

**Basic Info (please complete the following information):**
 - OS: Windows 10
 - Gitleaks Version: v7.3.0

**Additional context**
n/a

cc @zricethezav
