### ISSUE TITLE
Too many false positives

### ISSUE THREAD

**Issue by dudicoco** [zricethezav/gitleaks#575]
I have created the following rule for generic secrets:
```
[[rules]]
    description = "Generic Credential"
    regex = '''(?i)(dbpass|dbuser|secret|key|pass|guid|pw|token)(.{0,40})?([0-9a-zA-Z-_\/+!{}/=]{4,120})'''
    tags = ["Generic"]
    [[rules.Entropies]]
        Min = "3.9"
        Max = "5.5"
        Group = "2"
```

The following two configurations are used for testing the rule (contains dummy secrets):
```
# test real secrets
env:
  PASSWORD: dY^5Ke76gdSiF
  OPSGENIE_API_KEY_URL: https://api.opsgenie.com/v1/json/cloudwatch?apiKey=182663ax-3ccb-20c3-1097-3ol15d0wfu45
  OKTA_CLIENT_SECRET: LjBlsCPNJNDQ7gazunVyZu3f2y5sF69RJmdxec6v
  ANODOT_TOKEN: uvqcblfxi1d3ohvwjftgb59e3mba1x98
  GITHUB_TOKEN: 1mlcyz92suir2qzfimaeekzb1goo5lveam15hebm
```
```
# test false positives
env:
  PASSWORD: test
  OPSGENIE_API_KEY: test
  OPSGENIE_API_KEY_URL: https://api.opsgenie.com/v1/json/cloudwatch?apiKey=test
  OKTA_CLIENT_SECRET: test
  ANODOT_TOKEN: $(echo $ASSUME_ROLE_OUTPUT | jq -r .Credentials.SessionToken)
  GITHUB_TOKEN: os.getenv('AWS_SECRET_ACCESS_KEY')
```

When running the rule on the second configuration, the rule alerts on false positives:
```
{
	"line": "          OPSGENIE_API_KEY_URL: https://api.opsgenie.com/v1/json/cloudwatch?apiKey=test",
	"lineNumber": 17,
	"offender": "KEY_URL: https://api.opsgenie.com/v1/json/cloudwatch",
	"offenderEntropy": 4.325,
	"commit": "",
	"repo": "",
	"repoURL": "",
	"leakURL": "",
	"rule": "Generic Credential",
	"commitMessage": "",
	"author": "",
	"email": "",
	"file": ".",
	"date": "0001-01-01T00:00:00Z",
	"tags": "Generic"
}
{
	"line": "          ANODOT_TOKEN: $(echo $ASSUME_ROLE_OUTPUT | jq -r .Credentials.SessionToken)",
	"lineNumber": 19,
	"offender": "TOKEN: $(echo $ASSUME_ROLE_OUTPUT | jq -r .Credentials",
	"offenderEntropy": 4.465,
	"commit": "",
	"repo": "",
	"repoURL": "",
	"leakURL": "",
	"rule": "Generic Credential",
	"commitMessage": "",
	"author": "",
	"email": "",
	"file": ".",
	"date": "0001-01-01T00:00:00Z",
	"tags": "Generic"
}
{
	"line": "          GITHUB_TOKEN: os.getenv('AWS_SECRET_ACCESS_KEY')",
	"lineNumber": 20,
	"offender": "TOKEN: os.getenv('AWS_SECRET_ACCESS_KEY",
	"offenderEntropy": 4.123,
	"commit": "",
	"repo": "",
	"repoURL": "",
	"leakURL": "",
	"rule": "Generic Credential",
	"commitMessage": "",
	"author": "",
	"email": "",
	"file": ".",
	"date": "0001-01-01T00:00:00Z",
	"tags": "Generic"
}
```

Raising the min entropy value would cause the rule to not detect all secrets in the configuration with the "real" secrets.

In addition, it seems that the rule is calculating the entropy for the key as well, even though i've used `Group = "2"` within the rule.

What can be done in order to both find the real secrets and not find false positives?

Thanks
