### ISSUE TITLE
Not working well with pre-commit

### ISSUE THREAD

**Issue by chanpl** [zricethezav/gitleaks#595]
**Describe the bug**
Two issues I got when using gitleaks with pre-commit:

1. When run with `pre-commit run -a`, `gitleaks` was executed multiple times.
2. A single line of secret will generate more than one error under the same rule.

**To Reproduce**
To reproduce:
1. Add the following example secret to any file in your repo
`mongodb://myDBReader:D1fficultP%40ssw0rd@mongodb0.example.com:27017/?authSource=admin
`

2. Use this additional config
```$ cat .gitleaks.toml
[[rules]]
        description = "MONGODB URI"
        regex = '''mongodb:\/\/(.*):(.*)@(.*)'''
        tags = ["secrets"]
```

3. Add this hook to .pre-commit-config.yaml
```
    - repo: https://github.com/zricethezav/gitleaks
      rev: v7.5.0
      hooks:
          - id: gitleaks
            args: ["--additional-config", ".gitleaks.toml", "--verbose"]
```
5. Run `pre-commit run -a`

**Expected behavior**
`gitleaks` runs only once and just report 1 error. (Since there is only one line of secret)
