### ISSUE TITLE
sharable configuration

### ISSUE THREAD

**Issue by foolioo** [zricethezav/gitleaks#596]
gitleaks does not have a builtin functionality to share a configuration, this can be very helpful for sharing the same configuration across many projects. it would be neat that when http(s) url(s) is given to gitleaks, gitleaks will fetch the configuration over http(s) and append it.

alternatives:
- `config-path` can be overloaded to honor http(s) urls or introduce another option for it
- support for appending other configurations by urls\names in `.gitleaks.toml`, such as:

```toml
[[append]]
  list = ["default", "https://raw.githubusercontent.com/ShiftLeftSecurity/sast-scan/master/tools_config/credscan-config.toml"]
```

cc @zricethezav
