### ISSUE TITLE
GitLeaks locally is failing, but is passing on GitLab with the container from DockerHub

### ISSUE THREAD

**Issue by emmahsax** [zricethezav/gitleaks#606]
**Describe the bug**

I've defined a unique `gitleaks.toml` config file in the repository in question. This toml file has only a basic `allowlist` and has no rules defined. I'd like to take that config file and append it to the _default rules_ that come straight from GitLeaks.

Locally, (with a mac with GitLeaks installed from homebrew), GitLeaks fails because it's appending my custom toml with the rules from GitLeaks. Failure is expected result:

```
$ gitleaks -v --repo-url=https://gitlab.com/REDACTED/REDACTED --access-token='REDACTED' --additional-config='.gitlab/gitleaks.toml' 
INFO[0000] cloning... https://gitlab.com/REDACTED/REDACTED
Enumerating objects: 6581, done.
Counting objects: 100% (187/187), done.
Compressing objects: 100% (115/115), done.
Total 6581 (delta 106), reused 134 (delta 72), pack-reused 6394
{
        "line": "  NEW_VARIABLE=\"AKIAIO5FODNN7EXAMPLE\"",
        .
        .
        .
        "tags": "key, AWS"
}
INFO[0028] scan time: 7 seconds 964 milliseconds 357 microseconds 
INFO[0028] commits scanned: 1074                        
WARN[0028] leaks found: 3                
```

But when I commit and push that to the repository and run the CI with GitLab CI, it passes. It's passing (I presume) because it's no longer appending my custom toml to the default rules, but using _only_ my custom toml, which has no rules. So it seems that it is NOT appending my toml to the default rules even when it should.

On GitLab CI, I'm running the GitLeaks command through the DockerHub container:

```yml
gitleaks:
  stage: test
  image:
    name: zricethezav/gitleaks
    entrypoint: [""]
  script: gitleaks --verbose \
            --repo-url=$CI_PROJECT_URL \
            --access-token=$GITLAB_API_TOKEN \
            --additional-config='.gitlab/gitleaks.toml'
```

Here's my custom toml file:
```toml
title = "Custom GitLeaks Config"

[allowlist]
	description = "Files/Images/Commits to allow"
  commits = [
    "REDACTED",
    "REDACTED",
    "REDACTED"
  ]
	files = [
    '''(.*?)(png|jpg|gif|docx|pdf|xls|pyc|zip)$''',
    '''^\.?gitleaks.toml$''',
    '''(go.mod|go.sum)$'''
  ]
```

**To Reproduce**
1. Take a project on GitLab
2. Make a custom toml file and add a simple `allowlist` _with no rules_
3. Commit some fake secrets so that running GitLeaks locally fails
4. Make a `.gitlab-ci.yml` file and add a basic GitLeaks job
5. Commit and push to GitLab, and the GitLeaks job will succeed even though it fails locally

**Expected behavior**
When commits fail GitLeaks locally, they also fail GitLeaks on GitLab CI.

**Screenshots**

Here's a screenshot of the passing GitLab CI job:
![image](https://user-images.githubusercontent.com/7562793/130258706-940547ab-853f-4602-abe6-8e155dacf28a.png)

**Basic Info (please complete the following information):**
 - OS: Mac 11.5.2
 - Gitleaks Version: 7.5.0 locally, `latest` with DockerHub

**Additional context**

cc @zricethezav

**Comment by w0rmr1d3r** [comment]
Hello @emmahsax ,

Have you taken a look at -> https://github.com/zricethezav/gitleaks-action#using-your-own-gitleakstoml-configuration ?
Could it be related?

Could this be more of an issue with the action and not with gitleaks?

Cheers!

**Comment by emmahsax** [comment]
@w0rmr1d3r I am not using the gitleaks action at all.

**Comment by emmahsax** [comment]
My apologies. The issue was actually in my yaml. The following works:
```yaml
gitleaks:
  stage: test
  image:
    name: zricethezav/gitleaks
    entrypoint: [""]
  script: |
    gitleaks --verbose \
      --repo-url=$CI_PROJECT_URL \
      --access-token=$GITLAB_API_TOKEN \
      --additional-config='.gitlab/gitleaks.toml'
```
