### ISSUE TITLE
Reduce False Positives with Tree-sitter

### ISSUE THREAD

**Issue by zricethezav** [zricethezav/gitleaks#628]
**Is your feature request related to a problem? Please describe.**
False positives will pop up due to regex/entropy limitations. Having access to a syntax-tree during an additional rule validation step would help reduce false positives. We can use [tree-sitter](https://tree-sitter.github.io/tree-sitter/) for the parsing after a  leak has been detected.

**Describe the solution you'd like**
Leverage this [tree-sitter pkg](https://github.com/smacker/go-tree-sitter) to parse lines of code that ostensibly contain leaks. To increase confidence of gitleaks findings we should **validate that the offending regex match is contained with a string literal**.

To make development of this feature easier https://github.com/zricethezav/gitleaks/issues/618 should be completed before this issue.

cc @zricethezav

**Comment by zricethezav** [comment]
Eventually we could even replace the rules with a custom query language that queries tree-sitter parse results o.O

Treesitterplayground:  ![Screen Shot 2021-09-07 at 1 05 21 PM](https://user-images.githubusercontent.com/15034943/132390709-b7642568-55db-45d2-93f4-318250a3f54e.png)

Config idea:

```toml
title = "gitleaks config"

[regex]
twitter='[0-9a-z]{35,44}'

[[rules]]
    description='twitter client in call param'
    pattern='''
        $CALL($ARG=$twitter)
    '''
```
