### ISSUE TITLE
v7.6.0 makes a 'could not generate Patch' error

### ISSUE THREAD

**Issue by emmahsax** [zricethezav/gitleaks#630]
**Describe the bug**
When using the newest GitLeaks version (v7.6.0), I now am seeing a new error:

```
time="2021-09-08T15:37:19Z" level=info msg="opening ./\n"
time="2021-09-08T15:37:20Z" level=info msg="scan time: 1 second 67 milliseconds 150 microseconds"
time="2021-09-08T15:37:20Z" level=error msg="could not generate Patch"
```

Here's the run with v7.6.0: https://github.com/emmahsax/emmahsax.github.io/runs/3546589868?check_suite_focus=true

Here's the same run with v7.5.0: https://github.com/emmahsax/emmahsax.github.io/runs/3546602697?check_suite_focus=true

To get this, I'm running it with a `--path='./'` flag, and I'm passing in an additional config with a list of commits with the `--commits` flag.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Basic Info (please complete the following information):**
 - OS:
 - Gitleaks Version:

**Additional context**

cc @zricethezav

**Comment by zricethezav** [comment]
Thanks for opening this issue @emmahsax. I have a feeling this is related to bumping the dependencies which includes the diff library that `go-git` uses, https://github.com/zricethezav/gitleaks/blob/master/go.sum#L62

I'll try and figure out what's going on here

**Comment by w0rmr1d3r** [comment]
@zricethezav for that dependency, if I'm not mistaken, exists a new version -> https://github.com/sergi/go-diff/releases/tag/v1.2.0
Can we upgrade it and try again?

**Comment by emmahsax** [comment]
@zricethezav or @w0rmr1d3r Have either of you figured out what was going on? I've been doing some more poking around.

First off, I made https://github.com/zricethezav/gitleaks/pull/639, but I'm not sure how to test it beyond the automated tests... essentially because I haven't been able to reproduce this error locally at all.

When I run `gitleaks` installed via Brew (`7.5.0`, `7.6.0`, and `7.6.1`), the scan runs as expected (no error):
```bash
$ gitleaks -v --path='./' --additional-config='gitleaks.toml' --commits='4b18...e89'
INFO[0000] opening ./                                   
INFO[0002] scan time: 2 seconds 464 milliseconds 486 microseconds 
INFO[0002] commits scanned: 18                          
INFO[0002] No leaks found
```

When I run `gitleaks` through a docker container (`v7.5.0`, `v7.6.0`, and `v.7.6.1`), the scan runs as expected (no error):
```bash
$ docker run -v $(pwd):/app -it --entrypoint /bin/bash zricethezav/gitleaks:v.7.6.1
bash-5.1$ cd app
bash-5.1$ gitleaks -v --path='./' --additional-config='gitleaks.toml' --commits='4b18...e89'
INFO[0000] opening ./                                   
INFO[0002] scan time: 2 seconds 464 milliseconds 486 microseconds 
INFO[0002] commits scanned: 18                          
INFO[0002] No leaks found 
```

But somehow when I run it on GitHub Actions (**not using https://github.com/zricethezav/gitleaks-action**), it just breaks on a couple of repositories occasionally. Here is my full GH Action:

```yml
name: GitLeaks

# Override desired times to run this workflow
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

# Override environment variables as needed
env:
  GITLEAKS_CONFIG_COMMITS: "[]" # A list of commits to ignore when running GitLeaks
  GITLEAKS_CONFIG_REGEXES: "[]" # A list of regexes or secrets to ignore when running GitLeaks

###########################################################
### DO NOT EDIT BELOW – TEXT IS AUTOMATICALLY GENERATED ###
###########################################################

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set GitLeaks Config
        run: |
          if [[ ${{ github.REF }} == 'refs/heads/main' ]]; then
            CURRENT_COMMIT="${{ github.SHA }}"
          else
            CURRENT_COMMIT="${{ github.EVENT.PULL_REQUEST.HEAD.SHA }}"
          fi
          echo "COMMITS=$(
            git rev-list $CURRENT_COMMIT ^origin/main | sed 's/^\|$//g' | paste -sd, -
          )" >> $GITHUB_ENV
          echo "Title = 'GitLeaks Allowlist'" >> ${{ github.WORKSPACE }}/gitleaks.toml
          echo "[allowlist]" >> ${{ github.WORKSPACE }}/gitleaks.toml
          echo "  commits = ${{ env.GITLEAKS_CONFIG_COMMITS }}" >> ${{ github.WORKSPACE }}/gitleaks.toml
          echo "  regexes = ${{ env.GITLEAKS_CONFIG_REGEXES }}" >> ${{ github.WORKSPACE }}/gitleaks.toml
      - name: GitLeaks
        uses: addnab/docker-run-action@v3
        with:
          image: zricethezav/gitleaks
          options: -v ${{ github.WORKSPACE }}:/app
          run: |
            cd /app
            if [[ ${{ github.REF }} == 'refs/heads/main' ]]; then
              gitleaks --verbose --additional-config='gitleaks.toml' \
                --repo-url='${{ github.SERVER_URL }}/${{ github.REPOSITORY }}' \
                --access-token='${{ secrets.GITHUB_TOKEN }}'
            else
              gitleaks --verbose --additional-config='gitleaks.toml' \
                --path='./' --commits='${{ env.COMMITS }}'
            fi
```

**Comment by w0rmr1d3r** [comment]
Hello @emmahsax !
Weird situation, can we try if we run Gitleaks inside a GitHub action but using it like this:
```
docker run -v $(pwd):/app -it --entrypoint /bin/bash zricethezav/gitleaks:v.7.6.1
```
That is, to run it like that in this step:
```
- name: Set GitLeaks Config
```

Can we try that if it gives us the same error?

On the other side, this PR has its build failing -> https://github.com/zricethezav/gitleaks/pull/639
Haven't checked it though

**Comment by emmahsax** [comment]
@w0rmr1d3r This is what I changed it to:

```yml
- name: GitLeaks
  run: |
    docker pull zricethezav/gitleaks
    docker run --rm -v $(pwd):/app -i --entrypoint /bin/bash zricethezav/gitleaks -c " \
      cd /app && \
      if [[ ${{ github.REF }} == 'refs/heads/main' ]]; then \
        gitleaks --verbose --additional-config='gitleaks.toml' \
          --repo-url='${{ github.SERVER_URL }}/${{ github.REPOSITORY }}' \
          --access-token='${{ secrets.GITHUB_TOKEN }}'; \
      else \
        gitleaks --verbose --additional-config='gitleaks.toml' \
          --path='./' --commits='${{ env.COMMITS }}'; \
      fi \
    "
```

And just like when running it previously, versions 7.6.0 and 7.6.1 gave me the same error, while version 7.5.0 succeeded. So essentially this is the exactly same thing as when using the `addnab/docker-run-action@v3` GitHub Action to run GitLeaks.

HOWEVER, I did figure something potentially out. The issue may have to do with using the `--path` flag. I discovered that if I pull the repository from the GitHub URL (with the proper access token of course), then it works successfully:

```yml
- name: GitLeaks
  uses: addnab/docker-run-action@v3
  with:
    image: zricethezav/gitleaks
    options: -v ${{ github.WORKSPACE }}:/app
    run: |
      cd /app
      gitleaks --verbose --additional-config='gitleaks.toml' \
        --repo-url='${{ github.SERVER_URL }}/${{ github.REPOSITORY }}' \
        --access-token='${{ secrets.GITHUB_TOKEN }}' \
        --commits='${{ env.COMMITS }}'
```

Although it takes a bit longer to pull the entire repository history, this is a decent workaround for me and solves the issue.

However, it seems like perhaps the `--path` flag could be the issue after all, and I'm not sure what the proper debugging or fix for that would be.

**Comment by w0rmr1d3r** [comment]
Thanks @emmahsax :)

What if in the first example, you just put `--path='.'` instead of `--path='./'`.  Have you tried so?
Talking about these lines:
```bash
else \
        gitleaks --verbose --additional-config='gitleaks.toml' \
          --path='./' --commits='${{ env.COMMITS }}'; \
      fi \
```
Or maybe, you won't even need that `cd app/`, in this section of the readme -> https://github.com/zricethezav/gitleaks#docker
It's passing to the docker, the path without needing to do the `cd app/` that you are doing.

Can we try that? Those two variants?

Cheers!

**Comment by emmahsax** [comment]
All of that does work! I ended up changing the final solution to this:

```yml
- name: GitLeaks
  run: |
    COMMAND="gitleaks --verbose --additional-config='/app/gitleaks.toml' --path='/app'"
    if [ ${{ github.REF }} != 'refs/heads/main' ]; then
      COMMAND="${COMMAND} --commits='${{ env.COMMITS }}'"
    fi
    docker pull zricethezav/gitleaks
    docker run --rm -v $(pwd):/app -i --entrypoint /bin/bash zricethezav/gitleaks -c "$COMMAND"
```

It still does return the `could not generate Patch` error, but it moves on and finishes the scan anyway:

```
time="2021-09-17T02:56:30Z" level=info msg="opening /app\n"
time="2021-09-17T02:56:32Z" level=error msg="could not generate Patch"
time="2021-09-17T02:56:33Z" level=error msg="could not generate Patch"
time="2021-09-17T02:56:33Z" level=error msg="could not generate Patch"
time="2021-09-17T02:56:34Z" level=info msg="scan time: 3 seconds 660 milliseconds 924 microseconds"
time="2021-09-17T02:56:34Z" level=info msg="commits scanned: 257"
time="2021-09-17T02:56:34Z" level=info msg="No leaks found"
```

**Comment by w0rmr1d3r** [comment]
@zricethezav any help here? I know nothing about that error :/

**Comment by emmahsax** [comment]
@zricethezav I'm continuing to run into similar issues, but this time on GitLab CI:
```
time="2021-09-28T16:36:02Z" level=info msg="opening ./\n"
time="2021-09-28T16:36:04Z" level=info msg="scan time: 1 second 376 milliseconds 905 microseconds"
time="2021-09-28T16:36:04Z" level=error msg="could not generate Patch"
```

I've tried removing the `/` in the `--path` (same error), changing it from single-quotes to double-quotes (gitleaks ignored my commits because it couldn't find the object, which implied the commits weren't being interpolated correctly). I, again, think the path isn't being set properly. Lastly, it's again just an issue with `>= v7.6.0`, so version 7.5.0 continues to work as expected.

```yaml
gitleaks:
  image:
    name: zricethezav/gitleaks
    entrypoint: [""]
  variables:
    GIT_DEPTH: ''
  script: |
    commits=$(git rev-list $CI_COMMIT_SHA \
      ^origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME \
      | sed 's/^\|$//g' | paste -sd, -
    )
    gitleaks --verbose --path="./" --commits="$commits" --additional-config=".gitlab/ci/gitleaks.toml"
```
