### ISSUE TITLE
`pre-commit run -a` outputs different result to `gitleaks --repo-url .`

### ISSUE THREAD

**Issue by tumido** [zricethezav/gitleaks#657]
**Describe the bug**
Pre-commit's `run --all-files` should check on all files in the repo, including those which are already commited. `gitleaks` hook disregards already commited files and does not check them.

**To Reproduce**

1. Have a pre-commit hook enabled
```yaml
# .pre-commit-config.yaml
repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v7.6.1
    hooks:
      - id: gitleaks
        args: ["--verbose"]
```

2. Have a file with any secret violation e.g.:
```
AKIA0000000000000000
```
3. Commit the file (skipping pre-commit or disabling it)
4. Run `pre-commit run -a` and see that it passed without detecting any violation
5. Run `gitleaks --repo-url .` and see that it detected the violation properly

**Expected behavior**
I expect the `pre-commit run -a` with `gitleaks` hook to behave in the same way as `gitleaks --repo-url .`

**Screenshots**
![image](https://user-images.githubusercontent.com/7453394/136554911-aedb29ce-2296-4a1f-b698-e152be2e9d66.png)

**Basic Info (please complete the following information):**
 - OS: linux
 - Gitleaks Version: 7.6.1

**Additional context**
If `gitleaks` skips detection of secrets on already commited files, it's harder to introduce `gitleaks` hook as a new hook to existing repo. Because that's what pre-commit users do, when they add new hooks or upgrade them - they run the new hooks against all files to fix everything up. 

cc @zricethezav
