### ISSUE TITLE
config validation

### ISSUE THREAD

**Issue by zricethezav** [zricethezav/gitleaks#736]
**Is your feature request related to a problem? Please describe.**
It would be nice if gitleaks had a `validate` command that would validate examples found in the config rules. Introducing such a feature would speed up rule development and help with debugging.

**Describe the solution you'd like**
`example` entry in the `rules` tables
ex:
```toml
[[rules]]
id = "discord-client-secret"
description = "Discord client secret"
regex = '''(?i)(discord[a-z0-9_ .\-,]{0,25})(=|>|:=|\|\|:|<=|=>|:).{0,5}['\"]([a-z0-9=_\-]{32})['\"]'''
secretGroup = 3
examples=[
  '''discord_client_secret = "8dyfuiRyq=vVc3RRr_edRk-fK__JItpZ"'''
]
```
Running `gitleaks validate --config-path={path-to-config}` would validate all the rules with `examples` in their definitions. Target a specific rule by specifying the `--rule-id` flag: `gitleaks validate --config-path={path-to-config} --rule-id=discord-client-secret`

cc @zricethezav
