### ISSUE TITLE
Include rules for browser cookie databases in default config

### ISSUE THREAD

**Issue by lostatc** [zricethezav/gitleaks#739]
**Is your feature request related to a problem? Please describe.**

The Register [recently reported](https://www.theregister.com/2021/11/18/firefox_cookies_github/) that there's been an epidemic of GitHub users pushing their browser cookie databases as part of their public dotfiles repos, which is a problem because browser cookies often include authentication tokens. GitHub apparently isn't planning on addressing this via their [secret scanning](https://docs.github.com/en/code-security/secret-scanning/about-secret-scanning) program, and I think a tool like gitleaks could fill the gap for users who use GitHub for dotfiles.

**Describe the solution you'd like**

Rules to match the cookie databases for popular browsers could be added to the default gitleaks configuration. Rules for Firefox and Chromium might look like this:

```toml
[[rules]]
description = "Firefox cookies database"
file = '''^cookies\.sqlite$'''
regex = '''^SQLite format 3\x00'''

[[rules]]
description = "Chromium cookies database"
file = '''^Cookies$'''
regex = '''^SQLite format 3\x00'''
```

Both browsers use SQLite databases with static file names for their cookie databases, and SQLite databases can be detected via regex by their [file header](https://www.sqlite.org/fileformat.html).

**Describe alternatives you've considered**

Matching SQLite databases with a certain file name could lead to false positives. SQLite supports setting an [application ID](https://sqlite.org/pragma.html#pragma_application_id) in the database header, but neither Firefox nor Chromium seem to make use of this feature.

Because this problem is really only relevant for dotfiles repos, this might be out of scope for the project's default config. Having a wiki for documenting rules like this might be an alternative.

cc @zricethezav
