### ISSUE TITLE
Custom configuration always results in "no leaks found" or apparently doesn't extend default config?

### ISSUE THREAD

**Issue by jantari** [zricethezav/gitleaks#740]
**Describe the bug**
We have a repo with old secret leaks that have since been rotated and are no longer relevant.
I wanted to exclude the commits with these leaks as per the documentation, but whenever I run gitleaks
with the custom configuration file it reports "no leaks found" despite me only adding some of the commits
with leaks to the allowlist.

**To Reproduce**

1. Have a repo with multiple commits containing leaks
2. Ensure leaks are discovered by gitleaks in the default config (with `gitleaks detect . -v`)
3. Add the custom configuration to allowlist some or one commit with leaks:
```toml
title = "gitleaks config"

[allowlist]
description = "Some of our commits to ignore"
commits = [
    "example-commit-sha", # contains old secret, has been rotated
    "example-commit-sha" # contains old secret, has been rotated
]
```
4. run `gitleaks detect . -v` again
5. Output says "no leaks found"

**Expected behavior**
gitleaks should find all leaks except the ones from the specifically ignored / allowlisted commits.

**Screenshots**
I provided all configs and output as text, don't think further screenshots are needed.

**Basic Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Gitleaks Version: 8.1.1

**Additional context**
I believe the problem could be that the custom configuration file is REPLACING the entire default config rather than extending / being merged with it.

If that is the case, then the documentation is not clear - how does one just add an allowlist without getting rid of all rules? I obviously don't want to check all of gitleaks default config into our repository as the config would become outdated quickly, become incompatible with newer gitleaks versions, doesn't automatically add new rules and contains immense amount of bloat / default config that we don't need.

Can we specify a `.gitleaks.extends-default.toml` file or similar?

cc @zricethezav

**Comment by zricethezav** [comment]
> I believe the problem could be that the custom configuration file is REPLACING the entire default config rather than extending / being merged with it.

That is the case. Extending/merging is not supported right now but I am open to introducing that functionality in a future release. I need some time to think about how to do that. Perhaps something like 

```toml
title = "gitleaks config"

operation = "replace"

[[rules]]
id = "gitlab-pat"
description = "GitLab Personal Access Token"
regex = '''glpat-[0-9a-zA-Z\-]{20}'''
# ...
```

`operation` could either be "replace" or "append"

Please open a PR if you think the documentation is unclear. 

Closing this issue. Feel free to open another issue with a request to merge/append configs
