### ISSUE TITLE
Gitleaks ignoring git safe.directory

### ISSUE THREAD

**Issue by fnk0c** [zricethezav/gitleaks#844]
**Describe the bug**
When running `gitleaks` at `Gitlab CI` it returns the following error and workaround:
```
ERR fatal: unsafe repository ('/opt/src' is owned by someone else)
ERR To add an exception for this directory, call:
ERR 
ERR 	git config --global --add safe.directory /opt/src
```

However, the workaround doesn't seem to be taking effect as the error keeps happening.

**To Reproduce**
*gitlab-ci.yml file*

```
sast:gitleaks:
  extends: .external
  stage: security (sca/sast)
  script:
    - apk add git
    - make gitleaks
  artifacts:
    when: always
    reports:
      secret_detection: "$REPORT_PATH/secret-detection.json"
```

*Execution output*
```
touch "output/reports/secret-detection.json"
git config --global --add safe.directory /opt/src
docker run -v /builds/application:/opt/src \
	zricethezav/gitleaks:latest detect \
	--source "/opt/src" \
	--report-path "/opt/src/output/reports/secret-detection.json"
```

**Expected behavior**
Add directory to exception list and don't fail

**Screenshots**
![image](https://user-images.githubusercontent.com/8636581/163904557-ec7ec575-72ac-4ea2-b66a-bbc0bd13a214.png)

**Basic Info (please complete the following information):**
 - OS: gitlab-runner 14.9.0~beta.68.g1283960c
 - Gitleaks Version: 8.7.0

**Additional context**

cc @zricethezav

**Comment by tuan1986le** [comment]
Root cause: The owner of the directory is different than the (current) user, performing git/gitleaks
(as in the example below, `root` and `gitleaks`)

1. the first run `gitleaks detect --source "/src"` got error

the fix `git config --global --add safe.directory` should be placed at same docker/user as the `gitleaks ` command

2. the second run `gitleaks detect --source "/src"` is successful

```
$ docker run -it --entrypoint "" \
                 -v /home/ec2-user/Hello-World:/src \
                 zricethezav/gitleaks:latest bash
bash-5.1$ ls -lah /src
total 4K     
drwxr-xr-x    3 root     root          32 Apr 19 13:36 .
drwxr-xr-x    1 root     root          17 Apr 19 13:40 ..
drwxr-xr-x    8 root     root         163 Apr 19 13:36 .git
-rw-r--r--    1 root     root          13 Apr 19 13:36 README
bash-5.1$ id
uid=1000(gitleaks) gid=1000(gitleaks)
bash-5.1$ gitleaks detect --source "/src"

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks 

1:41PM ERR fatal: unsafe repository ('/src' is owned by someone else)
1:41PM ERR To add an exception for this directory, call:
1:41PM ERR 
1:41PM ERR      git config --global --add safe.directory /src
bash-5.1$ git config --global --add safe.directory /src
bash-5.1$ gitleaks detect --source "/src"

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks 

1:41PM INF scan completed in 56.652421ms
1:41PM INF no leaks found
bash-5.1$ 
```
fixing for `GitLab CI`:

- override `entrypoint` to run the fix `git config --global --add safe.directory`

```
test:
  stage: test
  image:
    name: zricethezav/gitleaks:latest
    entrypoint: [""]
  before_script:
    - git config --global --add safe.directory $CI_PROJECT_DIR
  script:
    - gitleaks detect 
```
