### ISSUE TITLE
Gits leaks doesn't detect base64 encode string

### ISSUE THREAD

**Issue by dileepdkumar** [zricethezav/gitleaks#856]
**Describe the bug**
Trying to detect base64 encode string in file that is committed to the Git.  but gitleaks doesn't detected thed base64 encode string

**To Reproduce**
File content:
#!/usr/bin/env python
import base64

# Replace the quoted text with the code you wish to decrypt.
coded_string = 'SG9va2VkIG9uIHBob25pY3Mgd29ya2VkIGZvciBtZQo='

# Decrypt the code string.
code_dump = base64.b64decode(coded_string)

# Print the decryption output to the screen.
print(code_dump)

# Print the decryption output a file.
f = open('base64_out.txt', 'w')
f.write(code_dump)
f.close()

**Expected behavior**
There should an rule to detect the base64 coded string in a commited file

**Screenshots**

**Basic Info (please complete the following information):**
 - OS: linux
 - Gitleaks Version: 8.8.2

**Additional context**

cc @zricethezav

**Comment by zricethezav** [comment]
@dileepdkumar Just to be clear you want me to detect the decoded string? So you're expecting Gitleaks to detect a base64 encoded string, decode it, and check if that decoded string contains a secret?

**Comment by sheeeng** [comment]
How does one detect any base64 encoded string?

I have tried the following two regex options, but to no avail.

```toml
[[rules]]
id = "base64-string"
description = "Base64 String"
regex = '''^(?:[A-Za-z0-9+\\/]{4})*(?:[A-Za-z0-9+\\/]{2}==|[A-Za-z0-9+\\/]{3}=|[A-Za-z0-9+\\/]{4})$'''
secretGroup = 0
keywords = [
    "base64",
]
```

```toml
[[rules]]
id = "base64-string"
description = "Base64 String"
regex = '''^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$'''
secretGroup = 0
keywords = [
    "base64",
]
```

I would like to detect the following strings.

```text
Qf6s4882E9wlVRqg3NDDqX1CcKWeDSghfiBTcIwmLvlS5jNm8IDHZQoUCjV7wHQRUDTGgBtXPqcYACDbkkahCA==
UMPbz88LKNc0tiedTLYv8IpokeBdFSxOjT0ImG7ch3WILJrnvn8tJrBzNdXXeJyS5UBVDZ6XJ80HACDbrz8HLw==
```
