### ISSUE TITLE
Using unaltered "zricethezav" config toml explicitly, leads somehow to way more findings

### ISSUE THREAD

**Issue by Vankog** [zricethezav/gitleaks#869]
**Describe the bug**
We plan to customize some rules. Thus, we naturally started by copying the default config from  
https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml  
and used it via   
`- gitleaks detect  -f json --redact -r ./secret-scan-results.json -c .config/gitleaks.toml` 
in our gitlab-ci.yml.

Much to my suprise, the findings went up from 86 to 102.

Gitleaks Version and copied toml do match: 
gitleaks docker image https://hub.docker.com/layers/zricethezav/gitleaks/v8.8.4/images/sha256-3e7186a08439aafd17405c787287ba2d6a1dd88344757c6209b1ce08f0d1be7e?context=explore 
=> v. 8.8.4), 
and toml on master at that time, matching release tag 8.8.4: https://github.com/zricethezav/gitleaks/releases/tag/v8.8.4
Of Course, the analyzed source code is at the same state as well. (except for the gitleaks config, that is)

**To Reproduce**
* Use Gitleaks 8.8.4 docker with `gitleaks detect  -f json --redact -r ./secret-scan-results.json`
* Copy https://github.com/zricethezav/gitleaks/blob/61ee7c58cc00840f2959f46fdf6f1bf860870f41/config/gitleaks.toml   
to /.config/ in your repo.   
(note: I am not sure if the leading dot makes a difference. We need it though. Otherwise gradle thinks this is a sub-project.)
* Use Gitleaks 8.8.4 docker with `gitleaks detect  -f json --redact -r ./secret-scan-results.json -c .config/gitleaks.toml`

Unfortunately, I am not able to provide you access to the repo in question. Sorry.

**Expected behavior**
The result should be the same.

**Basic Info (please complete the following information):**
hosted GitLab Community Edition 14.9.2
using gitlab-ci
with gitlab-ci.yml:

```yml
# GitLeaks Secret Scanning
stages:
  - secret-scan

gitleaks:
  stage: secret-scan
  image:
    name: "zricethezav/gitleaks:latest"
    entrypoint: [""]
  script:
    - git config --global --add safe.directory /builds/myGroup/myProject
    - gitleaks detect  -f json --redact -r ./secret-scan-results.json -c .config/gitleaks.toml
  artifacts:
    when: always
    expire_in: 1 day
    paths:
      - secret-scan-results.json
  timeout: 2 hours
  allow_failure: true

```

 - Gitleaks Version: 8.8.4 docker image, "latest" tag currently being: https://hub.docker.com/layers/zricethezav/gitleaks/v8.8.4/images/sha256-3e7186a08439aafd17405c787287ba2d6a1dd88344757c6209b1ce08f0d1be7e?context=explore

cc @zricethezav
