### ISSUE TITLE
Q&A : Best configuration between GitLab and GitHub

### ISSUE THREAD

**Issue by GridexX** [zricethezav/gitleaks#871]
## I was asking myself a question about difference between configuration file in GitHub and GitLab.

On this project [secrets](https://gitlab.com/gitlab-org/security-products/analyzers/secrets) on Gitlab, the configuration [file](https://gitlab.com/gitlab-org/security-products/analyzers/secrets/-/blob/f=e895e96a00baf4147b51761210df5b067dd37f5/gitleaks.toml) used for detecting secrets is differents from the default
[*gitleaks.toml*](https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml) on GitHub. *Why ?* Some rules concerning the same secret have different regex, for example 

### SendinBlue API token :

**In gitLab repo :**
```toml
[[rules]]
id = "Sendinblue API token"
description = "Sendinblue API token"
regex ='''xkeysib-[a-f0-9]{64}\-(?i)[a-z0-9]{16}'''
```

**In Github**
```toml
[[rules]]
description ="Sendinblue API token"
id ="sendinblue-api-token"
regex ='''(?i)\b(xkeysib-[a-f0-9]{64}\-(?i)[a-z0-9]{16})(?:['|\"|\n|\r|\s|\x60]|$)'''
secretGroup =1
keywords = [
"xkeysib-",
]
```
Thanks in advance for your help !
