### ISSUE TITLE
Opt-in validation option for configs

### ISSUE THREAD

**Issue by zricethezav** [zricethezav/gitleaks#932]
**Is your feature request related to a problem? Please describe.**
It would be nice to introduce a feature like the team at trufflesecurity did with trufflehog where they validate an api key automatically. I would like to do this using the configuration.

**Describe the solution you'd like**
I'm thinking something like:
```toml
[[rules]]
description = "Asana Client Secret"
id = "asana-client-secret"
regex = '''(?i)(?:asana)(?:[0-9a-z\-_\t .]{0,20})(?:[\s|']|[\s|"]){0,3}(?:=|>|:=|\|\|:|<=|=>|:)(?:'|\"|\s|=|\x60){0,5}([a-z0-9]{32})(?:['|\"|\n|\r|\s|\x60]|$)'''
secretGroup = 1
keywords = [
    "asana",
]

# ... 

[[validate]]
# docs https://developers.asana.com/docs
description = "Validation step for asana secrets"
url = "https://app.asana.com/api/1.0/users/me"
expectedStatus = 200
headers = {'Authorization'='Bearer ${asana-client-secret}'}
```

Some pseudo-code might look like:
```
retFindings = []
for each fragment:

    for each rule:
        findings = detect(fragment, rules)

    for each validate:
        validatedFindings = checkValidate(fragment, validate)

    retFindings = append(retfindings, filter(findings, validatedFindings)...)
```

**Describe alternatives you've considered**
n/a

**Additional context**
n/a for now

cc @zricethezav
