### ISSUE TITLE
print resulting configuration for debug purpose if extend directive is used

### ISSUE THREAD

**Issue by t3mi** [zricethezav/gitleaks#983]
**Is your feature request related to a problem? Please describe.**
If would be good for debug purpose to have an option to print/dump resulting configuration which would be used by the gitleaks tool when `extend` directive is used.
My use case - I have a few false positives which are triggered by deafult `generic-api-key`. So in attempts to minimize them I wanted to override entropy/allowlist values for this rule using the following config. But it seems that rule's other properties are vanished:

```toml
# entropy
title = "Gitleaks"

[extend]
useDefault = true

[[rules]]
id = "generic-api-key"
entropy = 4
```

```toml
# rule allowlist
title = "Gitleaks"

[extend]
useDefault = true

[[rules]]
id = "generic-api-key"
[rules.allowlist]
regexes = ['''ClientI[dD]''']
```

**Describe the solution you'd like**
Not sure if separate option is needed but printing config if log level output is set to `debug` would be more than enough.

**Describe alternatives you've considered**
Multiple try-outs with different config options until working global allowlist setting was found.

cc @zricethezav
